# Site settings
title: slim
baseurl: "/slim"
url: "http://syaning.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 

# Utils
mathjax: true